// This file is generated by tools/lang.py
// Do not edit manually

#[repr(C)]
pub enum Voice {
  #[allow(non_camel_case_types)]
  af_ZA_AdriNeural,
  #[allow(non_camel_case_types)]
  af_ZA_WillemNeural,
  #[allow(non_camel_case_types)]
  sq_AL_AnilaNeural,
  #[allow(non_camel_case_types)]
  sq_AL_IlirNeural,
  #[allow(non_camel_case_types)]
  am_ET_AmehaNeural,
  #[allow(non_camel_case_types)]
  am_ET_MekdesNeural,
  #[allow(non_camel_case_types)]
  ar_DZ_AminaNeural,
  #[allow(non_camel_case_types)]
  ar_DZ_IsmaelNeural,
  #[allow(non_camel_case_types)]
  ar_BH_AliNeural,
  #[allow(non_camel_case_types)]
  ar_BH_LailaNeural,
  #[allow(non_camel_case_types)]
  ar_EG_SalmaNeural,
  #[allow(non_camel_case_types)]
  ar_EG_ShakirNeural,
  #[allow(non_camel_case_types)]
  ar_IQ_BasselNeural,
  #[allow(non_camel_case_types)]
  ar_IQ_RanaNeural,
  #[allow(non_camel_case_types)]
  ar_JO_SanaNeural,
  #[allow(non_camel_case_types)]
  ar_JO_TaimNeural,
  #[allow(non_camel_case_types)]
  ar_KW_FahedNeural,
  #[allow(non_camel_case_types)]
  ar_KW_NouraNeural,
  #[allow(non_camel_case_types)]
  ar_LB_LaylaNeural,
  #[allow(non_camel_case_types)]
  ar_LB_RamiNeural,
  #[allow(non_camel_case_types)]
  ar_LY_ImanNeural,
  #[allow(non_camel_case_types)]
  ar_LY_OmarNeural,
  #[allow(non_camel_case_types)]
  ar_MA_JamalNeural,
  #[allow(non_camel_case_types)]
  ar_MA_MounaNeural,
  #[allow(non_camel_case_types)]
  ar_OM_AbdullahNeural,
  #[allow(non_camel_case_types)]
  ar_OM_AyshaNeural,
  #[allow(non_camel_case_types)]
  ar_QA_AmalNeural,
  #[allow(non_camel_case_types)]
  ar_QA_MoazNeural,
  #[allow(non_camel_case_types)]
  ar_SA_HamedNeural,
  #[allow(non_camel_case_types)]
  ar_SA_ZariyahNeural,
  #[allow(non_camel_case_types)]
  ar_SY_AmanyNeural,
  #[allow(non_camel_case_types)]
  ar_SY_LaithNeural,
  #[allow(non_camel_case_types)]
  ar_TN_HediNeural,
  #[allow(non_camel_case_types)]
  ar_TN_ReemNeural,
  #[allow(non_camel_case_types)]
  ar_AE_FatimaNeural,
  #[allow(non_camel_case_types)]
  ar_AE_HamdanNeural,
  #[allow(non_camel_case_types)]
  ar_YE_MaryamNeural,
  #[allow(non_camel_case_types)]
  ar_YE_SalehNeural,
  #[allow(non_camel_case_types)]
  az_AZ_BabekNeural,
  #[allow(non_camel_case_types)]
  az_AZ_BanuNeural,
  #[allow(non_camel_case_types)]
  bn_BD_NabanitaNeural,
  #[allow(non_camel_case_types)]
  bn_BD_PradeepNeural,
  #[allow(non_camel_case_types)]
  bn_IN_BashkarNeural,
  #[allow(non_camel_case_types)]
  bn_IN_TanishaaNeural,
  #[allow(non_camel_case_types)]
  bs_BA_GoranNeural,
  #[allow(non_camel_case_types)]
  bs_BA_VesnaNeural,
  #[allow(non_camel_case_types)]
  bg_BG_BorislavNeural,
  #[allow(non_camel_case_types)]
  bg_BG_KalinaNeural,
  #[allow(non_camel_case_types)]
  my_MM_NilarNeural,
  #[allow(non_camel_case_types)]
  my_MM_ThihaNeural,
  #[allow(non_camel_case_types)]
  ca_ES_EnricNeural,
  #[allow(non_camel_case_types)]
  ca_ES_JoanaNeural,
  #[allow(non_camel_case_types)]
  zh_HK_HiuGaaiNeural,
  #[allow(non_camel_case_types)]
  zh_HK_HiuMaanNeural,
  #[allow(non_camel_case_types)]
  zh_HK_WanLungNeural,
  #[allow(non_camel_case_types)]
  zh_CN_XiaoxiaoNeural,
  #[allow(non_camel_case_types)]
  zh_CN_XiaoyiNeural,
  #[allow(non_camel_case_types)]
  zh_CN_YunjianNeural,
  #[allow(non_camel_case_types)]
  zh_CN_YunxiNeural,
  #[allow(non_camel_case_types)]
  zh_CN_YunxiaNeural,
  #[allow(non_camel_case_types)]
  zh_CN_YunyangNeural,
  #[allow(non_camel_case_types)]
  zh_CN_liaoning_XiaobeiNeural,
  #[allow(non_camel_case_types)]
  zh_TW_HsiaoChenNeural,
  #[allow(non_camel_case_types)]
  zh_TW_YunJheNeural,
  #[allow(non_camel_case_types)]
  zh_TW_HsiaoYuNeural,
  #[allow(non_camel_case_types)]
  zh_CN_shaanxi_XiaoniNeural,
  #[allow(non_camel_case_types)]
  hr_HR_GabrijelaNeural,
  #[allow(non_camel_case_types)]
  hr_HR_SreckoNeural,
  #[allow(non_camel_case_types)]
  cs_CZ_AntoninNeural,
  #[allow(non_camel_case_types)]
  cs_CZ_VlastaNeural,
  #[allow(non_camel_case_types)]
  da_DK_ChristelNeural,
  #[allow(non_camel_case_types)]
  da_DK_JeppeNeural,
  #[allow(non_camel_case_types)]
  nl_BE_ArnaudNeural,
  #[allow(non_camel_case_types)]
  nl_BE_DenaNeural,
  #[allow(non_camel_case_types)]
  nl_NL_ColetteNeural,
  #[allow(non_camel_case_types)]
  nl_NL_FennaNeural,
  #[allow(non_camel_case_types)]
  nl_NL_MaartenNeural,
  #[allow(non_camel_case_types)]
  en_AU_NatashaNeural,
  #[allow(non_camel_case_types)]
  en_AU_WilliamNeural,
  #[allow(non_camel_case_types)]
  en_CA_ClaraNeural,
  #[allow(non_camel_case_types)]
  en_CA_LiamNeural,
  #[allow(non_camel_case_types)]
  en_HK_SamNeural,
  #[allow(non_camel_case_types)]
  en_HK_YanNeural,
  #[allow(non_camel_case_types)]
  en_IN_NeerjaExpressiveNeural,
  #[allow(non_camel_case_types)]
  en_IN_NeerjaNeural,
  #[allow(non_camel_case_types)]
  en_IN_PrabhatNeural,
  #[allow(non_camel_case_types)]
  en_IE_ConnorNeural,
  #[allow(non_camel_case_types)]
  en_IE_EmilyNeural,
  #[allow(non_camel_case_types)]
  en_KE_AsiliaNeural,
  #[allow(non_camel_case_types)]
  en_KE_ChilembaNeural,
  #[allow(non_camel_case_types)]
  en_NZ_MitchellNeural,
  #[allow(non_camel_case_types)]
  en_NZ_MollyNeural,
  #[allow(non_camel_case_types)]
  en_NG_AbeoNeural,
  #[allow(non_camel_case_types)]
  en_NG_EzinneNeural,
  #[allow(non_camel_case_types)]
  en_PH_JamesNeural,
  #[allow(non_camel_case_types)]
  en_PH_RosaNeural,
  #[allow(non_camel_case_types)]
  en_SG_LunaNeural,
  #[allow(non_camel_case_types)]
  en_SG_WayneNeural,
  #[allow(non_camel_case_types)]
  en_ZA_LeahNeural,
  #[allow(non_camel_case_types)]
  en_ZA_LukeNeural,
  #[allow(non_camel_case_types)]
  en_TZ_ElimuNeural,
  #[allow(non_camel_case_types)]
  en_TZ_ImaniNeural,
  #[allow(non_camel_case_types)]
  en_GB_LibbyNeural,
  #[allow(non_camel_case_types)]
  en_GB_MaisieNeural,
  #[allow(non_camel_case_types)]
  en_GB_RyanNeural,
  #[allow(non_camel_case_types)]
  en_GB_SoniaNeural,
  #[allow(non_camel_case_types)]
  en_GB_ThomasNeural,
  #[allow(non_camel_case_types)]
  en_US_AriaNeural,
  #[allow(non_camel_case_types)]
  en_US_AnaNeural,
  #[allow(non_camel_case_types)]
  en_US_ChristopherNeural,
  #[allow(non_camel_case_types)]
  en_US_EricNeural,
  #[allow(non_camel_case_types)]
  en_US_GuyNeural,
  #[allow(non_camel_case_types)]
  en_US_JennyNeural,
  #[allow(non_camel_case_types)]
  en_US_MichelleNeural,
  #[allow(non_camel_case_types)]
  en_US_RogerNeural,
  #[allow(non_camel_case_types)]
  en_US_SteffanNeural,
  #[allow(non_camel_case_types)]
  et_EE_AnuNeural,
  #[allow(non_camel_case_types)]
  et_EE_KertNeural,
  #[allow(non_camel_case_types)]
  fil_PH_AngeloNeural,
  #[allow(non_camel_case_types)]
  fil_PH_BlessicaNeural,
  #[allow(non_camel_case_types)]
  fi_FI_HarriNeural,
  #[allow(non_camel_case_types)]
  fi_FI_NooraNeural,
  #[allow(non_camel_case_types)]
  fr_BE_CharlineNeural,
  #[allow(non_camel_case_types)]
  fr_BE_GerardNeural,
  #[allow(non_camel_case_types)]
  fr_CA_AntoineNeural,
  #[allow(non_camel_case_types)]
  fr_CA_JeanNeural,
  #[allow(non_camel_case_types)]
  fr_CA_SylvieNeural,
  #[allow(non_camel_case_types)]
  fr_FR_DeniseNeural,
  #[allow(non_camel_case_types)]
  fr_FR_EloiseNeural,
  #[allow(non_camel_case_types)]
  fr_FR_HenriNeural,
  #[allow(non_camel_case_types)]
  fr_CH_ArianeNeural,
  #[allow(non_camel_case_types)]
  fr_CH_FabriceNeural,
  #[allow(non_camel_case_types)]
  gl_ES_RoiNeural,
  #[allow(non_camel_case_types)]
  gl_ES_SabelaNeural,
  #[allow(non_camel_case_types)]
  ka_GE_EkaNeural,
  #[allow(non_camel_case_types)]
  ka_GE_GiorgiNeural,
  #[allow(non_camel_case_types)]
  de_AT_IngridNeural,
  #[allow(non_camel_case_types)]
  de_AT_JonasNeural,
  #[allow(non_camel_case_types)]
  de_DE_AmalaNeural,
  #[allow(non_camel_case_types)]
  de_DE_ConradNeural,
  #[allow(non_camel_case_types)]
  de_DE_KatjaNeural,
  #[allow(non_camel_case_types)]
  de_DE_KillianNeural,
  #[allow(non_camel_case_types)]
  de_CH_JanNeural,
  #[allow(non_camel_case_types)]
  de_CH_LeniNeural,
  #[allow(non_camel_case_types)]
  el_GR_AthinaNeural,
  #[allow(non_camel_case_types)]
  el_GR_NestorasNeural,
  #[allow(non_camel_case_types)]
  gu_IN_DhwaniNeural,
  #[allow(non_camel_case_types)]
  gu_IN_NiranjanNeural,
  #[allow(non_camel_case_types)]
  he_IL_AvriNeural,
  #[allow(non_camel_case_types)]
  he_IL_HilaNeural,
  #[allow(non_camel_case_types)]
  hi_IN_MadhurNeural,
  #[allow(non_camel_case_types)]
  hi_IN_SwaraNeural,
  #[allow(non_camel_case_types)]
  hu_HU_NoemiNeural,
  #[allow(non_camel_case_types)]
  hu_HU_TamasNeural,
  #[allow(non_camel_case_types)]
  is_IS_GudrunNeural,
  #[allow(non_camel_case_types)]
  is_IS_GunnarNeural,
  #[allow(non_camel_case_types)]
  id_ID_ArdiNeural,
  #[allow(non_camel_case_types)]
  id_ID_GadisNeural,
  #[allow(non_camel_case_types)]
  ga_IE_ColmNeural,
  #[allow(non_camel_case_types)]
  ga_IE_OrlaNeural,
  #[allow(non_camel_case_types)]
  it_IT_DiegoNeural,
  #[allow(non_camel_case_types)]
  it_IT_ElsaNeural,
  #[allow(non_camel_case_types)]
  it_IT_IsabellaNeural,
  #[allow(non_camel_case_types)]
  ja_JP_KeitaNeural,
  #[allow(non_camel_case_types)]
  ja_JP_NanamiNeural,
  #[allow(non_camel_case_types)]
  jv_ID_DimasNeural,
  #[allow(non_camel_case_types)]
  jv_ID_SitiNeural,
  #[allow(non_camel_case_types)]
  kn_IN_GaganNeural,
  #[allow(non_camel_case_types)]
  kn_IN_SapnaNeural,
  #[allow(non_camel_case_types)]
  kk_KZ_AigulNeural,
  #[allow(non_camel_case_types)]
  kk_KZ_DauletNeural,
  #[allow(non_camel_case_types)]
  km_KH_PisethNeural,
  #[allow(non_camel_case_types)]
  km_KH_SreymomNeural,
  #[allow(non_camel_case_types)]
  ko_KR_InJoonNeural,
  #[allow(non_camel_case_types)]
  ko_KR_SunHiNeural,
  #[allow(non_camel_case_types)]
  lo_LA_ChanthavongNeural,
  #[allow(non_camel_case_types)]
  lo_LA_KeomanyNeural,
  #[allow(non_camel_case_types)]
  lv_LV_EveritaNeural,
  #[allow(non_camel_case_types)]
  lv_LV_NilsNeural,
  #[allow(non_camel_case_types)]
  lt_LT_LeonasNeural,
  #[allow(non_camel_case_types)]
  lt_LT_OnaNeural,
  #[allow(non_camel_case_types)]
  mk_MK_AleksandarNeural,
  #[allow(non_camel_case_types)]
  mk_MK_MarijaNeural,
  #[allow(non_camel_case_types)]
  ms_MY_OsmanNeural,
  #[allow(non_camel_case_types)]
  ms_MY_YasminNeural,
  #[allow(non_camel_case_types)]
  ml_IN_MidhunNeural,
  #[allow(non_camel_case_types)]
  ml_IN_SobhanaNeural,
  #[allow(non_camel_case_types)]
  mt_MT_GraceNeural,
  #[allow(non_camel_case_types)]
  mt_MT_JosephNeural,
  #[allow(non_camel_case_types)]
  mr_IN_AarohiNeural,
  #[allow(non_camel_case_types)]
  mr_IN_ManoharNeural,
  #[allow(non_camel_case_types)]
  mn_MN_BataaNeural,
  #[allow(non_camel_case_types)]
  mn_MN_YesuiNeural,
  #[allow(non_camel_case_types)]
  ne_NP_HemkalaNeural,
  #[allow(non_camel_case_types)]
  ne_NP_SagarNeural,
  #[allow(non_camel_case_types)]
  nb_NO_FinnNeural,
  #[allow(non_camel_case_types)]
  nb_NO_PernilleNeural,
  #[allow(non_camel_case_types)]
  ps_AF_GulNawazNeural,
  #[allow(non_camel_case_types)]
  ps_AF_LatifaNeural,
  #[allow(non_camel_case_types)]
  fa_IR_DilaraNeural,
  #[allow(non_camel_case_types)]
  fa_IR_FaridNeural,
  #[allow(non_camel_case_types)]
  pl_PL_MarekNeural,
  #[allow(non_camel_case_types)]
  pl_PL_ZofiaNeural,
  #[allow(non_camel_case_types)]
  pt_BR_AntonioNeural,
  #[allow(non_camel_case_types)]
  pt_BR_FranciscaNeural,
  #[allow(non_camel_case_types)]
  pt_PT_DuarteNeural,
  #[allow(non_camel_case_types)]
  pt_PT_RaquelNeural,
  #[allow(non_camel_case_types)]
  ro_RO_AlinaNeural,
  #[allow(non_camel_case_types)]
  ro_RO_EmilNeural,
  #[allow(non_camel_case_types)]
  ru_RU_DmitryNeural,
  #[allow(non_camel_case_types)]
  ru_RU_SvetlanaNeural,
  #[allow(non_camel_case_types)]
  sr_RS_NicholasNeural,
  #[allow(non_camel_case_types)]
  sr_RS_SophieNeural,
  #[allow(non_camel_case_types)]
  si_LK_SameeraNeural,
  #[allow(non_camel_case_types)]
  si_LK_ThiliniNeural,
  #[allow(non_camel_case_types)]
  sk_SK_LukasNeural,
  #[allow(non_camel_case_types)]
  sk_SK_ViktoriaNeural,
  #[allow(non_camel_case_types)]
  sl_SI_PetraNeural,
  #[allow(non_camel_case_types)]
  sl_SI_RokNeural,
  #[allow(non_camel_case_types)]
  so_SO_MuuseNeural,
  #[allow(non_camel_case_types)]
  so_SO_UbaxNeural,
  #[allow(non_camel_case_types)]
  es_AR_ElenaNeural,
  #[allow(non_camel_case_types)]
  es_AR_TomasNeural,
  #[allow(non_camel_case_types)]
  es_BO_MarceloNeural,
  #[allow(non_camel_case_types)]
  es_BO_SofiaNeural,
  #[allow(non_camel_case_types)]
  es_CL_CatalinaNeural,
  #[allow(non_camel_case_types)]
  es_CL_LorenzoNeural,
  #[allow(non_camel_case_types)]
  es_CO_GonzaloNeural,
  #[allow(non_camel_case_types)]
  es_CO_SalomeNeural,
  #[allow(non_camel_case_types)]
  es_CR_JuanNeural,
  #[allow(non_camel_case_types)]
  es_CR_MariaNeural,
  #[allow(non_camel_case_types)]
  es_CU_BelkysNeural,
  #[allow(non_camel_case_types)]
  es_CU_ManuelNeural,
  #[allow(non_camel_case_types)]
  es_DO_EmilioNeural,
  #[allow(non_camel_case_types)]
  es_DO_RamonaNeural,
  #[allow(non_camel_case_types)]
  es_EC_AndreaNeural,
  #[allow(non_camel_case_types)]
  es_EC_LuisNeural,
  #[allow(non_camel_case_types)]
  es_SV_LorenaNeural,
  #[allow(non_camel_case_types)]
  es_SV_RodrigoNeural,
  #[allow(non_camel_case_types)]
  es_GQ_JavierNeural,
  #[allow(non_camel_case_types)]
  es_GQ_TeresaNeural,
  #[allow(non_camel_case_types)]
  es_GT_AndresNeural,
  #[allow(non_camel_case_types)]
  es_GT_MartaNeural,
  #[allow(non_camel_case_types)]
  es_HN_CarlosNeural,
  #[allow(non_camel_case_types)]
  es_HN_KarlaNeural,
  #[allow(non_camel_case_types)]
  es_MX_DaliaNeural,
  #[allow(non_camel_case_types)]
  es_MX_JorgeNeural,
  #[allow(non_camel_case_types)]
  es_NI_FedericoNeural,
  #[allow(non_camel_case_types)]
  es_NI_YolandaNeural,
  #[allow(non_camel_case_types)]
  es_PA_MargaritaNeural,
  #[allow(non_camel_case_types)]
  es_PA_RobertoNeural,
  #[allow(non_camel_case_types)]
  es_PY_MarioNeural,
  #[allow(non_camel_case_types)]
  es_PY_TaniaNeural,
  #[allow(non_camel_case_types)]
  es_PE_AlexNeural,
  #[allow(non_camel_case_types)]
  es_PE_CamilaNeural,
  #[allow(non_camel_case_types)]
  es_PR_KarinaNeural,
  #[allow(non_camel_case_types)]
  es_PR_VictorNeural,
  #[allow(non_camel_case_types)]
  es_ES_AlvaroNeural,
  #[allow(non_camel_case_types)]
  es_ES_ElviraNeural,
  #[allow(non_camel_case_types)]
  es_US_AlonsoNeural,
  #[allow(non_camel_case_types)]
  es_US_PalomaNeural,
  #[allow(non_camel_case_types)]
  es_UY_MateoNeural,
  #[allow(non_camel_case_types)]
  es_UY_ValentinaNeural,
  #[allow(non_camel_case_types)]
  es_VE_PaolaNeural,
  #[allow(non_camel_case_types)]
  es_VE_SebastianNeural,
  #[allow(non_camel_case_types)]
  su_ID_JajangNeural,
  #[allow(non_camel_case_types)]
  su_ID_TutiNeural,
  #[allow(non_camel_case_types)]
  sw_KE_RafikiNeural,
  #[allow(non_camel_case_types)]
  sw_KE_ZuriNeural,
  #[allow(non_camel_case_types)]
  sw_TZ_DaudiNeural,
  #[allow(non_camel_case_types)]
  sw_TZ_RehemaNeural,
  #[allow(non_camel_case_types)]
  sv_SE_MattiasNeural,
  #[allow(non_camel_case_types)]
  sv_SE_SofieNeural,
  #[allow(non_camel_case_types)]
  ta_IN_PallaviNeural,
  #[allow(non_camel_case_types)]
  ta_IN_ValluvarNeural,
  #[allow(non_camel_case_types)]
  ta_MY_KaniNeural,
  #[allow(non_camel_case_types)]
  ta_MY_SuryaNeural,
  #[allow(non_camel_case_types)]
  ta_SG_AnbuNeural,
  #[allow(non_camel_case_types)]
  ta_SG_VenbaNeural,
  #[allow(non_camel_case_types)]
  ta_LK_KumarNeural,
  #[allow(non_camel_case_types)]
  ta_LK_SaranyaNeural,
  #[allow(non_camel_case_types)]
  te_IN_MohanNeural,
  #[allow(non_camel_case_types)]
  te_IN_ShrutiNeural,
  #[allow(non_camel_case_types)]
  th_TH_NiwatNeural,
  #[allow(non_camel_case_types)]
  th_TH_PremwadeeNeural,
  #[allow(non_camel_case_types)]
  tr_TR_AhmetNeural,
  #[allow(non_camel_case_types)]
  tr_TR_EmelNeural,
  #[allow(non_camel_case_types)]
  uk_UA_OstapNeural,
  #[allow(non_camel_case_types)]
  uk_UA_PolinaNeural,
  #[allow(non_camel_case_types)]
  ur_IN_GulNeural,
  #[allow(non_camel_case_types)]
  ur_IN_SalmanNeural,
  #[allow(non_camel_case_types)]
  ur_PK_AsadNeural,
  #[allow(non_camel_case_types)]
  ur_PK_UzmaNeural,
  #[allow(non_camel_case_types)]
  uz_UZ_MadinaNeural,
  #[allow(non_camel_case_types)]
  uz_UZ_SardorNeural,
  #[allow(non_camel_case_types)]
  vi_VN_HoaiMyNeural,
  #[allow(non_camel_case_types)]
  vi_VN_NamMinhNeural,
  #[allow(non_camel_case_types)]
  cy_GB_AledNeural,
  #[allow(non_camel_case_types)]
  cy_GB_NiaNeural,
  #[allow(non_camel_case_types)]
  zu_ZA_ThandoNeural,
  #[allow(non_camel_case_types)]
  zu_ZA_ThembaNeural
}

impl From<Voice> for &str {
    fn from(voice: Voice) -> Self {
        match voice {
           Voice::af_ZA_AdriNeural => {"Microsoft Server Speech Text to Speech Voice (af-ZA, AdriNeural)"}
           Voice::af_ZA_WillemNeural => {"Microsoft Server Speech Text to Speech Voice (af-ZA, WillemNeural)"}
           Voice::sq_AL_AnilaNeural => {"Microsoft Server Speech Text to Speech Voice (sq-AL, AnilaNeural)"}
           Voice::sq_AL_IlirNeural => {"Microsoft Server Speech Text to Speech Voice (sq-AL, IlirNeural)"}
           Voice::am_ET_AmehaNeural => {"Microsoft Server Speech Text to Speech Voice (am-ET, AmehaNeural)"}
           Voice::am_ET_MekdesNeural => {"Microsoft Server Speech Text to Speech Voice (am-ET, MekdesNeural)"}
           Voice::ar_DZ_AminaNeural => {"Microsoft Server Speech Text to Speech Voice (ar-DZ, AminaNeural)"}
           Voice::ar_DZ_IsmaelNeural => {"Microsoft Server Speech Text to Speech Voice (ar-DZ, IsmaelNeural)"}
           Voice::ar_BH_AliNeural => {"Microsoft Server Speech Text to Speech Voice (ar-BH, AliNeural)"}
           Voice::ar_BH_LailaNeural => {"Microsoft Server Speech Text to Speech Voice (ar-BH, LailaNeural)"}
           Voice::ar_EG_SalmaNeural => {"Microsoft Server Speech Text to Speech Voice (ar-EG, SalmaNeural)"}
           Voice::ar_EG_ShakirNeural => {"Microsoft Server Speech Text to Speech Voice (ar-EG, ShakirNeural)"}
           Voice::ar_IQ_BasselNeural => {"Microsoft Server Speech Text to Speech Voice (ar-IQ, BasselNeural)"}
           Voice::ar_IQ_RanaNeural => {"Microsoft Server Speech Text to Speech Voice (ar-IQ, RanaNeural)"}
           Voice::ar_JO_SanaNeural => {"Microsoft Server Speech Text to Speech Voice (ar-JO, SanaNeural)"}
           Voice::ar_JO_TaimNeural => {"Microsoft Server Speech Text to Speech Voice (ar-JO, TaimNeural)"}
           Voice::ar_KW_FahedNeural => {"Microsoft Server Speech Text to Speech Voice (ar-KW, FahedNeural)"}
           Voice::ar_KW_NouraNeural => {"Microsoft Server Speech Text to Speech Voice (ar-KW, NouraNeural)"}
           Voice::ar_LB_LaylaNeural => {"Microsoft Server Speech Text to Speech Voice (ar-LB, LaylaNeural)"}
           Voice::ar_LB_RamiNeural => {"Microsoft Server Speech Text to Speech Voice (ar-LB, RamiNeural)"}
           Voice::ar_LY_ImanNeural => {"Microsoft Server Speech Text to Speech Voice (ar-LY, ImanNeural)"}
           Voice::ar_LY_OmarNeural => {"Microsoft Server Speech Text to Speech Voice (ar-LY, OmarNeural)"}
           Voice::ar_MA_JamalNeural => {"Microsoft Server Speech Text to Speech Voice (ar-MA, JamalNeural)"}
           Voice::ar_MA_MounaNeural => {"Microsoft Server Speech Text to Speech Voice (ar-MA, MounaNeural)"}
           Voice::ar_OM_AbdullahNeural => {"Microsoft Server Speech Text to Speech Voice (ar-OM, AbdullahNeural)"}
           Voice::ar_OM_AyshaNeural => {"Microsoft Server Speech Text to Speech Voice (ar-OM, AyshaNeural)"}
           Voice::ar_QA_AmalNeural => {"Microsoft Server Speech Text to Speech Voice (ar-QA, AmalNeural)"}
           Voice::ar_QA_MoazNeural => {"Microsoft Server Speech Text to Speech Voice (ar-QA, MoazNeural)"}
           Voice::ar_SA_HamedNeural => {"Microsoft Server Speech Text to Speech Voice (ar-SA, HamedNeural)"}
           Voice::ar_SA_ZariyahNeural => {"Microsoft Server Speech Text to Speech Voice (ar-SA, ZariyahNeural)"}
           Voice::ar_SY_AmanyNeural => {"Microsoft Server Speech Text to Speech Voice (ar-SY, AmanyNeural)"}
           Voice::ar_SY_LaithNeural => {"Microsoft Server Speech Text to Speech Voice (ar-SY, LaithNeural)"}
           Voice::ar_TN_HediNeural => {"Microsoft Server Speech Text to Speech Voice (ar-TN, HediNeural)"}
           Voice::ar_TN_ReemNeural => {"Microsoft Server Speech Text to Speech Voice (ar-TN, ReemNeural)"}
           Voice::ar_AE_FatimaNeural => {"Microsoft Server Speech Text to Speech Voice (ar-AE, FatimaNeural)"}
           Voice::ar_AE_HamdanNeural => {"Microsoft Server Speech Text to Speech Voice (ar-AE, HamdanNeural)"}
           Voice::ar_YE_MaryamNeural => {"Microsoft Server Speech Text to Speech Voice (ar-YE, MaryamNeural)"}
           Voice::ar_YE_SalehNeural => {"Microsoft Server Speech Text to Speech Voice (ar-YE, SalehNeural)"}
           Voice::az_AZ_BabekNeural => {"Microsoft Server Speech Text to Speech Voice (az-AZ, BabekNeural)"}
           Voice::az_AZ_BanuNeural => {"Microsoft Server Speech Text to Speech Voice (az-AZ, BanuNeural)"}
           Voice::bn_BD_NabanitaNeural => {"Microsoft Server Speech Text to Speech Voice (bn-BD, NabanitaNeural)"}
           Voice::bn_BD_PradeepNeural => {"Microsoft Server Speech Text to Speech Voice (bn-BD, PradeepNeural)"}
           Voice::bn_IN_BashkarNeural => {"Microsoft Server Speech Text to Speech Voice (bn-IN, BashkarNeural)"}
           Voice::bn_IN_TanishaaNeural => {"Microsoft Server Speech Text to Speech Voice (bn-IN, TanishaaNeural)"}
           Voice::bs_BA_GoranNeural => {"Microsoft Server Speech Text to Speech Voice (bs-BA, GoranNeural)"}
           Voice::bs_BA_VesnaNeural => {"Microsoft Server Speech Text to Speech Voice (bs-BA, VesnaNeural)"}
           Voice::bg_BG_BorislavNeural => {"Microsoft Server Speech Text to Speech Voice (bg-BG, BorislavNeural)"}
           Voice::bg_BG_KalinaNeural => {"Microsoft Server Speech Text to Speech Voice (bg-BG, KalinaNeural)"}
           Voice::my_MM_NilarNeural => {"Microsoft Server Speech Text to Speech Voice (my-MM, NilarNeural)"}
           Voice::my_MM_ThihaNeural => {"Microsoft Server Speech Text to Speech Voice (my-MM, ThihaNeural)"}
           Voice::ca_ES_EnricNeural => {"Microsoft Server Speech Text to Speech Voice (ca-ES, EnricNeural)"}
           Voice::ca_ES_JoanaNeural => {"Microsoft Server Speech Text to Speech Voice (ca-ES, JoanaNeural)"}
           Voice::zh_HK_HiuGaaiNeural => {"Microsoft Server Speech Text to Speech Voice (zh-HK, HiuGaaiNeural)"}
           Voice::zh_HK_HiuMaanNeural => {"Microsoft Server Speech Text to Speech Voice (zh-HK, HiuMaanNeural)"}
           Voice::zh_HK_WanLungNeural => {"Microsoft Server Speech Text to Speech Voice (zh-HK, WanLungNeural)"}
           Voice::zh_CN_XiaoxiaoNeural => {"Microsoft Server Speech Text to Speech Voice (zh-CN, XiaoxiaoNeural)"}
           Voice::zh_CN_XiaoyiNeural => {"Microsoft Server Speech Text to Speech Voice (zh-CN, XiaoyiNeural)"}
           Voice::zh_CN_YunjianNeural => {"Microsoft Server Speech Text to Speech Voice (zh-CN, YunjianNeural)"}
           Voice::zh_CN_YunxiNeural => {"Microsoft Server Speech Text to Speech Voice (zh-CN, YunxiNeural)"}
           Voice::zh_CN_YunxiaNeural => {"Microsoft Server Speech Text to Speech Voice (zh-CN, YunxiaNeural)"}
           Voice::zh_CN_YunyangNeural => {"Microsoft Server Speech Text to Speech Voice (zh-CN, YunyangNeural)"}
           Voice::zh_CN_liaoning_XiaobeiNeural => {"Microsoft Server Speech Text to Speech Voice (zh-CN-liaoning, XiaobeiNeural)"}
           Voice::zh_TW_HsiaoChenNeural => {"Microsoft Server Speech Text to Speech Voice (zh-TW, HsiaoChenNeural)"}
           Voice::zh_TW_YunJheNeural => {"Microsoft Server Speech Text to Speech Voice (zh-TW, YunJheNeural)"}
           Voice::zh_TW_HsiaoYuNeural => {"Microsoft Server Speech Text to Speech Voice (zh-TW, HsiaoYuNeural)"}
           Voice::zh_CN_shaanxi_XiaoniNeural => {"Microsoft Server Speech Text to Speech Voice (zh-CN-shaanxi, XiaoniNeural)"}
           Voice::hr_HR_GabrijelaNeural => {"Microsoft Server Speech Text to Speech Voice (hr-HR, GabrijelaNeural)"}
           Voice::hr_HR_SreckoNeural => {"Microsoft Server Speech Text to Speech Voice (hr-HR, SreckoNeural)"}
           Voice::cs_CZ_AntoninNeural => {"Microsoft Server Speech Text to Speech Voice (cs-CZ, AntoninNeural)"}
           Voice::cs_CZ_VlastaNeural => {"Microsoft Server Speech Text to Speech Voice (cs-CZ, VlastaNeural)"}
           Voice::da_DK_ChristelNeural => {"Microsoft Server Speech Text to Speech Voice (da-DK, ChristelNeural)"}
           Voice::da_DK_JeppeNeural => {"Microsoft Server Speech Text to Speech Voice (da-DK, JeppeNeural)"}
           Voice::nl_BE_ArnaudNeural => {"Microsoft Server Speech Text to Speech Voice (nl-BE, ArnaudNeural)"}
           Voice::nl_BE_DenaNeural => {"Microsoft Server Speech Text to Speech Voice (nl-BE, DenaNeural)"}
           Voice::nl_NL_ColetteNeural => {"Microsoft Server Speech Text to Speech Voice (nl-NL, ColetteNeural)"}
           Voice::nl_NL_FennaNeural => {"Microsoft Server Speech Text to Speech Voice (nl-NL, FennaNeural)"}
           Voice::nl_NL_MaartenNeural => {"Microsoft Server Speech Text to Speech Voice (nl-NL, MaartenNeural)"}
           Voice::en_AU_NatashaNeural => {"Microsoft Server Speech Text to Speech Voice (en-AU, NatashaNeural)"}
           Voice::en_AU_WilliamNeural => {"Microsoft Server Speech Text to Speech Voice (en-AU, WilliamNeural)"}
           Voice::en_CA_ClaraNeural => {"Microsoft Server Speech Text to Speech Voice (en-CA, ClaraNeural)"}
           Voice::en_CA_LiamNeural => {"Microsoft Server Speech Text to Speech Voice (en-CA, LiamNeural)"}
           Voice::en_HK_SamNeural => {"Microsoft Server Speech Text to Speech Voice (en-HK, SamNeural)"}
           Voice::en_HK_YanNeural => {"Microsoft Server Speech Text to Speech Voice (en-HK, YanNeural)"}
           Voice::en_IN_NeerjaExpressiveNeural => {"Microsoft Server Speech Text to Speech Voice (en-IN, NeerjaExpressiveNeural)"}
           Voice::en_IN_NeerjaNeural => {"Microsoft Server Speech Text to Speech Voice (en-IN, NeerjaNeural)"}
           Voice::en_IN_PrabhatNeural => {"Microsoft Server Speech Text to Speech Voice (en-IN, PrabhatNeural)"}
           Voice::en_IE_ConnorNeural => {"Microsoft Server Speech Text to Speech Voice (en-IE, ConnorNeural)"}
           Voice::en_IE_EmilyNeural => {"Microsoft Server Speech Text to Speech Voice (en-IE, EmilyNeural)"}
           Voice::en_KE_AsiliaNeural => {"Microsoft Server Speech Text to Speech Voice (en-KE, AsiliaNeural)"}
           Voice::en_KE_ChilembaNeural => {"Microsoft Server Speech Text to Speech Voice (en-KE, ChilembaNeural)"}
           Voice::en_NZ_MitchellNeural => {"Microsoft Server Speech Text to Speech Voice (en-NZ, MitchellNeural)"}
           Voice::en_NZ_MollyNeural => {"Microsoft Server Speech Text to Speech Voice (en-NZ, MollyNeural)"}
           Voice::en_NG_AbeoNeural => {"Microsoft Server Speech Text to Speech Voice (en-NG, AbeoNeural)"}
           Voice::en_NG_EzinneNeural => {"Microsoft Server Speech Text to Speech Voice (en-NG, EzinneNeural)"}
           Voice::en_PH_JamesNeural => {"Microsoft Server Speech Text to Speech Voice (en-PH, JamesNeural)"}
           Voice::en_PH_RosaNeural => {"Microsoft Server Speech Text to Speech Voice (en-PH, RosaNeural)"}
           Voice::en_SG_LunaNeural => {"Microsoft Server Speech Text to Speech Voice (en-SG, LunaNeural)"}
           Voice::en_SG_WayneNeural => {"Microsoft Server Speech Text to Speech Voice (en-SG, WayneNeural)"}
           Voice::en_ZA_LeahNeural => {"Microsoft Server Speech Text to Speech Voice (en-ZA, LeahNeural)"}
           Voice::en_ZA_LukeNeural => {"Microsoft Server Speech Text to Speech Voice (en-ZA, LukeNeural)"}
           Voice::en_TZ_ElimuNeural => {"Microsoft Server Speech Text to Speech Voice (en-TZ, ElimuNeural)"}
           Voice::en_TZ_ImaniNeural => {"Microsoft Server Speech Text to Speech Voice (en-TZ, ImaniNeural)"}
           Voice::en_GB_LibbyNeural => {"Microsoft Server Speech Text to Speech Voice (en-GB, LibbyNeural)"}
           Voice::en_GB_MaisieNeural => {"Microsoft Server Speech Text to Speech Voice (en-GB, MaisieNeural)"}
           Voice::en_GB_RyanNeural => {"Microsoft Server Speech Text to Speech Voice (en-GB, RyanNeural)"}
           Voice::en_GB_SoniaNeural => {"Microsoft Server Speech Text to Speech Voice (en-GB, SoniaNeural)"}
           Voice::en_GB_ThomasNeural => {"Microsoft Server Speech Text to Speech Voice (en-GB, ThomasNeural)"}
           Voice::en_US_AriaNeural => {"Microsoft Server Speech Text to Speech Voice (en-US, AriaNeural)"}
           Voice::en_US_AnaNeural => {"Microsoft Server Speech Text to Speech Voice (en-US, AnaNeural)"}
           Voice::en_US_ChristopherNeural => {"Microsoft Server Speech Text to Speech Voice (en-US, ChristopherNeural)"}
           Voice::en_US_EricNeural => {"Microsoft Server Speech Text to Speech Voice (en-US, EricNeural)"}
           Voice::en_US_GuyNeural => {"Microsoft Server Speech Text to Speech Voice (en-US, GuyNeural)"}
           Voice::en_US_JennyNeural => {"Microsoft Server Speech Text to Speech Voice (en-US, JennyNeural)"}
           Voice::en_US_MichelleNeural => {"Microsoft Server Speech Text to Speech Voice (en-US, MichelleNeural)"}
           Voice::en_US_RogerNeural => {"Microsoft Server Speech Text to Speech Voice (en-US, RogerNeural)"}
           Voice::en_US_SteffanNeural => {"Microsoft Server Speech Text to Speech Voice (en-US, SteffanNeural)"}
           Voice::et_EE_AnuNeural => {"Microsoft Server Speech Text to Speech Voice (et-EE, AnuNeural)"}
           Voice::et_EE_KertNeural => {"Microsoft Server Speech Text to Speech Voice (et-EE, KertNeural)"}
           Voice::fil_PH_AngeloNeural => {"Microsoft Server Speech Text to Speech Voice (fil-PH, AngeloNeural)"}
           Voice::fil_PH_BlessicaNeural => {"Microsoft Server Speech Text to Speech Voice (fil-PH, BlessicaNeural)"}
           Voice::fi_FI_HarriNeural => {"Microsoft Server Speech Text to Speech Voice (fi-FI, HarriNeural)"}
           Voice::fi_FI_NooraNeural => {"Microsoft Server Speech Text to Speech Voice (fi-FI, NooraNeural)"}
           Voice::fr_BE_CharlineNeural => {"Microsoft Server Speech Text to Speech Voice (fr-BE, CharlineNeural)"}
           Voice::fr_BE_GerardNeural => {"Microsoft Server Speech Text to Speech Voice (fr-BE, GerardNeural)"}
           Voice::fr_CA_AntoineNeural => {"Microsoft Server Speech Text to Speech Voice (fr-CA, AntoineNeural)"}
           Voice::fr_CA_JeanNeural => {"Microsoft Server Speech Text to Speech Voice (fr-CA, JeanNeural)"}
           Voice::fr_CA_SylvieNeural => {"Microsoft Server Speech Text to Speech Voice (fr-CA, SylvieNeural)"}
           Voice::fr_FR_DeniseNeural => {"Microsoft Server Speech Text to Speech Voice (fr-FR, DeniseNeural)"}
           Voice::fr_FR_EloiseNeural => {"Microsoft Server Speech Text to Speech Voice (fr-FR, EloiseNeural)"}
           Voice::fr_FR_HenriNeural => {"Microsoft Server Speech Text to Speech Voice (fr-FR, HenriNeural)"}
           Voice::fr_CH_ArianeNeural => {"Microsoft Server Speech Text to Speech Voice (fr-CH, ArianeNeural)"}
           Voice::fr_CH_FabriceNeural => {"Microsoft Server Speech Text to Speech Voice (fr-CH, FabriceNeural)"}
           Voice::gl_ES_RoiNeural => {"Microsoft Server Speech Text to Speech Voice (gl-ES, RoiNeural)"}
           Voice::gl_ES_SabelaNeural => {"Microsoft Server Speech Text to Speech Voice (gl-ES, SabelaNeural)"}
           Voice::ka_GE_EkaNeural => {"Microsoft Server Speech Text to Speech Voice (ka-GE, EkaNeural)"}
           Voice::ka_GE_GiorgiNeural => {"Microsoft Server Speech Text to Speech Voice (ka-GE, GiorgiNeural)"}
           Voice::de_AT_IngridNeural => {"Microsoft Server Speech Text to Speech Voice (de-AT, IngridNeural)"}
           Voice::de_AT_JonasNeural => {"Microsoft Server Speech Text to Speech Voice (de-AT, JonasNeural)"}
           Voice::de_DE_AmalaNeural => {"Microsoft Server Speech Text to Speech Voice (de-DE, AmalaNeural)"}
           Voice::de_DE_ConradNeural => {"Microsoft Server Speech Text to Speech Voice (de-DE, ConradNeural)"}
           Voice::de_DE_KatjaNeural => {"Microsoft Server Speech Text to Speech Voice (de-DE, KatjaNeural)"}
           Voice::de_DE_KillianNeural => {"Microsoft Server Speech Text to Speech Voice (de-DE, KillianNeural)"}
           Voice::de_CH_JanNeural => {"Microsoft Server Speech Text to Speech Voice (de-CH, JanNeural)"}
           Voice::de_CH_LeniNeural => {"Microsoft Server Speech Text to Speech Voice (de-CH, LeniNeural)"}
           Voice::el_GR_AthinaNeural => {"Microsoft Server Speech Text to Speech Voice (el-GR, AthinaNeural)"}
           Voice::el_GR_NestorasNeural => {"Microsoft Server Speech Text to Speech Voice (el-GR, NestorasNeural)"}
           Voice::gu_IN_DhwaniNeural => {"Microsoft Server Speech Text to Speech Voice (gu-IN, DhwaniNeural)"}
           Voice::gu_IN_NiranjanNeural => {"Microsoft Server Speech Text to Speech Voice (gu-IN, NiranjanNeural)"}
           Voice::he_IL_AvriNeural => {"Microsoft Server Speech Text to Speech Voice (he-IL, AvriNeural)"}
           Voice::he_IL_HilaNeural => {"Microsoft Server Speech Text to Speech Voice (he-IL, HilaNeural)"}
           Voice::hi_IN_MadhurNeural => {"Microsoft Server Speech Text to Speech Voice (hi-IN, MadhurNeural)"}
           Voice::hi_IN_SwaraNeural => {"Microsoft Server Speech Text to Speech Voice (hi-IN, SwaraNeural)"}
           Voice::hu_HU_NoemiNeural => {"Microsoft Server Speech Text to Speech Voice (hu-HU, NoemiNeural)"}
           Voice::hu_HU_TamasNeural => {"Microsoft Server Speech Text to Speech Voice (hu-HU, TamasNeural)"}
           Voice::is_IS_GudrunNeural => {"Microsoft Server Speech Text to Speech Voice (is-IS, GudrunNeural)"}
           Voice::is_IS_GunnarNeural => {"Microsoft Server Speech Text to Speech Voice (is-IS, GunnarNeural)"}
           Voice::id_ID_ArdiNeural => {"Microsoft Server Speech Text to Speech Voice (id-ID, ArdiNeural)"}
           Voice::id_ID_GadisNeural => {"Microsoft Server Speech Text to Speech Voice (id-ID, GadisNeural)"}
           Voice::ga_IE_ColmNeural => {"Microsoft Server Speech Text to Speech Voice (ga-IE, ColmNeural)"}
           Voice::ga_IE_OrlaNeural => {"Microsoft Server Speech Text to Speech Voice (ga-IE, OrlaNeural)"}
           Voice::it_IT_DiegoNeural => {"Microsoft Server Speech Text to Speech Voice (it-IT, DiegoNeural)"}
           Voice::it_IT_ElsaNeural => {"Microsoft Server Speech Text to Speech Voice (it-IT, ElsaNeural)"}
           Voice::it_IT_IsabellaNeural => {"Microsoft Server Speech Text to Speech Voice (it-IT, IsabellaNeural)"}
           Voice::ja_JP_KeitaNeural => {"Microsoft Server Speech Text to Speech Voice (ja-JP, KeitaNeural)"}
           Voice::ja_JP_NanamiNeural => {"Microsoft Server Speech Text to Speech Voice (ja-JP, NanamiNeural)"}
           Voice::jv_ID_DimasNeural => {"Microsoft Server Speech Text to Speech Voice (jv-ID, DimasNeural)"}
           Voice::jv_ID_SitiNeural => {"Microsoft Server Speech Text to Speech Voice (jv-ID, SitiNeural)"}
           Voice::kn_IN_GaganNeural => {"Microsoft Server Speech Text to Speech Voice (kn-IN, GaganNeural)"}
           Voice::kn_IN_SapnaNeural => {"Microsoft Server Speech Text to Speech Voice (kn-IN, SapnaNeural)"}
           Voice::kk_KZ_AigulNeural => {"Microsoft Server Speech Text to Speech Voice (kk-KZ, AigulNeural)"}
           Voice::kk_KZ_DauletNeural => {"Microsoft Server Speech Text to Speech Voice (kk-KZ, DauletNeural)"}
           Voice::km_KH_PisethNeural => {"Microsoft Server Speech Text to Speech Voice (km-KH, PisethNeural)"}
           Voice::km_KH_SreymomNeural => {"Microsoft Server Speech Text to Speech Voice (km-KH, SreymomNeural)"}
           Voice::ko_KR_InJoonNeural => {"Microsoft Server Speech Text to Speech Voice (ko-KR, InJoonNeural)"}
           Voice::ko_KR_SunHiNeural => {"Microsoft Server Speech Text to Speech Voice (ko-KR, SunHiNeural)"}
           Voice::lo_LA_ChanthavongNeural => {"Microsoft Server Speech Text to Speech Voice (lo-LA, ChanthavongNeural)"}
           Voice::lo_LA_KeomanyNeural => {"Microsoft Server Speech Text to Speech Voice (lo-LA, KeomanyNeural)"}
           Voice::lv_LV_EveritaNeural => {"Microsoft Server Speech Text to Speech Voice (lv-LV, EveritaNeural)"}
           Voice::lv_LV_NilsNeural => {"Microsoft Server Speech Text to Speech Voice (lv-LV, NilsNeural)"}
           Voice::lt_LT_LeonasNeural => {"Microsoft Server Speech Text to Speech Voice (lt-LT, LeonasNeural)"}
           Voice::lt_LT_OnaNeural => {"Microsoft Server Speech Text to Speech Voice (lt-LT, OnaNeural)"}
           Voice::mk_MK_AleksandarNeural => {"Microsoft Server Speech Text to Speech Voice (mk-MK, AleksandarNeural)"}
           Voice::mk_MK_MarijaNeural => {"Microsoft Server Speech Text to Speech Voice (mk-MK, MarijaNeural)"}
           Voice::ms_MY_OsmanNeural => {"Microsoft Server Speech Text to Speech Voice (ms-MY, OsmanNeural)"}
           Voice::ms_MY_YasminNeural => {"Microsoft Server Speech Text to Speech Voice (ms-MY, YasminNeural)"}
           Voice::ml_IN_MidhunNeural => {"Microsoft Server Speech Text to Speech Voice (ml-IN, MidhunNeural)"}
           Voice::ml_IN_SobhanaNeural => {"Microsoft Server Speech Text to Speech Voice (ml-IN, SobhanaNeural)"}
           Voice::mt_MT_GraceNeural => {"Microsoft Server Speech Text to Speech Voice (mt-MT, GraceNeural)"}
           Voice::mt_MT_JosephNeural => {"Microsoft Server Speech Text to Speech Voice (mt-MT, JosephNeural)"}
           Voice::mr_IN_AarohiNeural => {"Microsoft Server Speech Text to Speech Voice (mr-IN, AarohiNeural)"}
           Voice::mr_IN_ManoharNeural => {"Microsoft Server Speech Text to Speech Voice (mr-IN, ManoharNeural)"}
           Voice::mn_MN_BataaNeural => {"Microsoft Server Speech Text to Speech Voice (mn-MN, BataaNeural)"}
           Voice::mn_MN_YesuiNeural => {"Microsoft Server Speech Text to Speech Voice (mn-MN, YesuiNeural)"}
           Voice::ne_NP_HemkalaNeural => {"Microsoft Server Speech Text to Speech Voice (ne-NP, HemkalaNeural)"}
           Voice::ne_NP_SagarNeural => {"Microsoft Server Speech Text to Speech Voice (ne-NP, SagarNeural)"}
           Voice::nb_NO_FinnNeural => {"Microsoft Server Speech Text to Speech Voice (nb-NO, FinnNeural)"}
           Voice::nb_NO_PernilleNeural => {"Microsoft Server Speech Text to Speech Voice (nb-NO, PernilleNeural)"}
           Voice::ps_AF_GulNawazNeural => {"Microsoft Server Speech Text to Speech Voice (ps-AF, GulNawazNeural)"}
           Voice::ps_AF_LatifaNeural => {"Microsoft Server Speech Text to Speech Voice (ps-AF, LatifaNeural)"}
           Voice::fa_IR_DilaraNeural => {"Microsoft Server Speech Text to Speech Voice (fa-IR, DilaraNeural)"}
           Voice::fa_IR_FaridNeural => {"Microsoft Server Speech Text to Speech Voice (fa-IR, FaridNeural)"}
           Voice::pl_PL_MarekNeural => {"Microsoft Server Speech Text to Speech Voice (pl-PL, MarekNeural)"}
           Voice::pl_PL_ZofiaNeural => {"Microsoft Server Speech Text to Speech Voice (pl-PL, ZofiaNeural)"}
           Voice::pt_BR_AntonioNeural => {"Microsoft Server Speech Text to Speech Voice (pt-BR, AntonioNeural)"}
           Voice::pt_BR_FranciscaNeural => {"Microsoft Server Speech Text to Speech Voice (pt-BR, FranciscaNeural)"}
           Voice::pt_PT_DuarteNeural => {"Microsoft Server Speech Text to Speech Voice (pt-PT, DuarteNeural)"}
           Voice::pt_PT_RaquelNeural => {"Microsoft Server Speech Text to Speech Voice (pt-PT, RaquelNeural)"}
           Voice::ro_RO_AlinaNeural => {"Microsoft Server Speech Text to Speech Voice (ro-RO, AlinaNeural)"}
           Voice::ro_RO_EmilNeural => {"Microsoft Server Speech Text to Speech Voice (ro-RO, EmilNeural)"}
           Voice::ru_RU_DmitryNeural => {"Microsoft Server Speech Text to Speech Voice (ru-RU, DmitryNeural)"}
           Voice::ru_RU_SvetlanaNeural => {"Microsoft Server Speech Text to Speech Voice (ru-RU, SvetlanaNeural)"}
           Voice::sr_RS_NicholasNeural => {"Microsoft Server Speech Text to Speech Voice (sr-RS, NicholasNeural)"}
           Voice::sr_RS_SophieNeural => {"Microsoft Server Speech Text to Speech Voice (sr-RS, SophieNeural)"}
           Voice::si_LK_SameeraNeural => {"Microsoft Server Speech Text to Speech Voice (si-LK, SameeraNeural)"}
           Voice::si_LK_ThiliniNeural => {"Microsoft Server Speech Text to Speech Voice (si-LK, ThiliniNeural)"}
           Voice::sk_SK_LukasNeural => {"Microsoft Server Speech Text to Speech Voice (sk-SK, LukasNeural)"}
           Voice::sk_SK_ViktoriaNeural => {"Microsoft Server Speech Text to Speech Voice (sk-SK, ViktoriaNeural)"}
           Voice::sl_SI_PetraNeural => {"Microsoft Server Speech Text to Speech Voice (sl-SI, PetraNeural)"}
           Voice::sl_SI_RokNeural => {"Microsoft Server Speech Text to Speech Voice (sl-SI, RokNeural)"}
           Voice::so_SO_MuuseNeural => {"Microsoft Server Speech Text to Speech Voice (so-SO, MuuseNeural)"}
           Voice::so_SO_UbaxNeural => {"Microsoft Server Speech Text to Speech Voice (so-SO, UbaxNeural)"}
           Voice::es_AR_ElenaNeural => {"Microsoft Server Speech Text to Speech Voice (es-AR, ElenaNeural)"}
           Voice::es_AR_TomasNeural => {"Microsoft Server Speech Text to Speech Voice (es-AR, TomasNeural)"}
           Voice::es_BO_MarceloNeural => {"Microsoft Server Speech Text to Speech Voice (es-BO, MarceloNeural)"}
           Voice::es_BO_SofiaNeural => {"Microsoft Server Speech Text to Speech Voice (es-BO, SofiaNeural)"}
           Voice::es_CL_CatalinaNeural => {"Microsoft Server Speech Text to Speech Voice (es-CL, CatalinaNeural)"}
           Voice::es_CL_LorenzoNeural => {"Microsoft Server Speech Text to Speech Voice (es-CL, LorenzoNeural)"}
           Voice::es_CO_GonzaloNeural => {"Microsoft Server Speech Text to Speech Voice (es-CO, GonzaloNeural)"}
           Voice::es_CO_SalomeNeural => {"Microsoft Server Speech Text to Speech Voice (es-CO, SalomeNeural)"}
           Voice::es_CR_JuanNeural => {"Microsoft Server Speech Text to Speech Voice (es-CR, JuanNeural)"}
           Voice::es_CR_MariaNeural => {"Microsoft Server Speech Text to Speech Voice (es-CR, MariaNeural)"}
           Voice::es_CU_BelkysNeural => {"Microsoft Server Speech Text to Speech Voice (es-CU, BelkysNeural)"}
           Voice::es_CU_ManuelNeural => {"Microsoft Server Speech Text to Speech Voice (es-CU, ManuelNeural)"}
           Voice::es_DO_EmilioNeural => {"Microsoft Server Speech Text to Speech Voice (es-DO, EmilioNeural)"}
           Voice::es_DO_RamonaNeural => {"Microsoft Server Speech Text to Speech Voice (es-DO, RamonaNeural)"}
           Voice::es_EC_AndreaNeural => {"Microsoft Server Speech Text to Speech Voice (es-EC, AndreaNeural)"}
           Voice::es_EC_LuisNeural => {"Microsoft Server Speech Text to Speech Voice (es-EC, LuisNeural)"}
           Voice::es_SV_LorenaNeural => {"Microsoft Server Speech Text to Speech Voice (es-SV, LorenaNeural)"}
           Voice::es_SV_RodrigoNeural => {"Microsoft Server Speech Text to Speech Voice (es-SV, RodrigoNeural)"}
           Voice::es_GQ_JavierNeural => {"Microsoft Server Speech Text to Speech Voice (es-GQ, JavierNeural)"}
           Voice::es_GQ_TeresaNeural => {"Microsoft Server Speech Text to Speech Voice (es-GQ, TeresaNeural)"}
           Voice::es_GT_AndresNeural => {"Microsoft Server Speech Text to Speech Voice (es-GT, AndresNeural)"}
           Voice::es_GT_MartaNeural => {"Microsoft Server Speech Text to Speech Voice (es-GT, MartaNeural)"}
           Voice::es_HN_CarlosNeural => {"Microsoft Server Speech Text to Speech Voice (es-HN, CarlosNeural)"}
           Voice::es_HN_KarlaNeural => {"Microsoft Server Speech Text to Speech Voice (es-HN, KarlaNeural)"}
           Voice::es_MX_DaliaNeural => {"Microsoft Server Speech Text to Speech Voice (es-MX, DaliaNeural)"}
           Voice::es_MX_JorgeNeural => {"Microsoft Server Speech Text to Speech Voice (es-MX, JorgeNeural)"}
           Voice::es_NI_FedericoNeural => {"Microsoft Server Speech Text to Speech Voice (es-NI, FedericoNeural)"}
           Voice::es_NI_YolandaNeural => {"Microsoft Server Speech Text to Speech Voice (es-NI, YolandaNeural)"}
           Voice::es_PA_MargaritaNeural => {"Microsoft Server Speech Text to Speech Voice (es-PA, MargaritaNeural)"}
           Voice::es_PA_RobertoNeural => {"Microsoft Server Speech Text to Speech Voice (es-PA, RobertoNeural)"}
           Voice::es_PY_MarioNeural => {"Microsoft Server Speech Text to Speech Voice (es-PY, MarioNeural)"}
           Voice::es_PY_TaniaNeural => {"Microsoft Server Speech Text to Speech Voice (es-PY, TaniaNeural)"}
           Voice::es_PE_AlexNeural => {"Microsoft Server Speech Text to Speech Voice (es-PE, AlexNeural)"}
           Voice::es_PE_CamilaNeural => {"Microsoft Server Speech Text to Speech Voice (es-PE, CamilaNeural)"}
           Voice::es_PR_KarinaNeural => {"Microsoft Server Speech Text to Speech Voice (es-PR, KarinaNeural)"}
           Voice::es_PR_VictorNeural => {"Microsoft Server Speech Text to Speech Voice (es-PR, VictorNeural)"}
           Voice::es_ES_AlvaroNeural => {"Microsoft Server Speech Text to Speech Voice (es-ES, AlvaroNeural)"}
           Voice::es_ES_ElviraNeural => {"Microsoft Server Speech Text to Speech Voice (es-ES, ElviraNeural)"}
           Voice::es_US_AlonsoNeural => {"Microsoft Server Speech Text to Speech Voice (es-US, AlonsoNeural)"}
           Voice::es_US_PalomaNeural => {"Microsoft Server Speech Text to Speech Voice (es-US, PalomaNeural)"}
           Voice::es_UY_MateoNeural => {"Microsoft Server Speech Text to Speech Voice (es-UY, MateoNeural)"}
           Voice::es_UY_ValentinaNeural => {"Microsoft Server Speech Text to Speech Voice (es-UY, ValentinaNeural)"}
           Voice::es_VE_PaolaNeural => {"Microsoft Server Speech Text to Speech Voice (es-VE, PaolaNeural)"}
           Voice::es_VE_SebastianNeural => {"Microsoft Server Speech Text to Speech Voice (es-VE, SebastianNeural)"}
           Voice::su_ID_JajangNeural => {"Microsoft Server Speech Text to Speech Voice (su-ID, JajangNeural)"}
           Voice::su_ID_TutiNeural => {"Microsoft Server Speech Text to Speech Voice (su-ID, TutiNeural)"}
           Voice::sw_KE_RafikiNeural => {"Microsoft Server Speech Text to Speech Voice (sw-KE, RafikiNeural)"}
           Voice::sw_KE_ZuriNeural => {"Microsoft Server Speech Text to Speech Voice (sw-KE, ZuriNeural)"}
           Voice::sw_TZ_DaudiNeural => {"Microsoft Server Speech Text to Speech Voice (sw-TZ, DaudiNeural)"}
           Voice::sw_TZ_RehemaNeural => {"Microsoft Server Speech Text to Speech Voice (sw-TZ, RehemaNeural)"}
           Voice::sv_SE_MattiasNeural => {"Microsoft Server Speech Text to Speech Voice (sv-SE, MattiasNeural)"}
           Voice::sv_SE_SofieNeural => {"Microsoft Server Speech Text to Speech Voice (sv-SE, SofieNeural)"}
           Voice::ta_IN_PallaviNeural => {"Microsoft Server Speech Text to Speech Voice (ta-IN, PallaviNeural)"}
           Voice::ta_IN_ValluvarNeural => {"Microsoft Server Speech Text to Speech Voice (ta-IN, ValluvarNeural)"}
           Voice::ta_MY_KaniNeural => {"Microsoft Server Speech Text to Speech Voice (ta-MY, KaniNeural)"}
           Voice::ta_MY_SuryaNeural => {"Microsoft Server Speech Text to Speech Voice (ta-MY, SuryaNeural)"}
           Voice::ta_SG_AnbuNeural => {"Microsoft Server Speech Text to Speech Voice (ta-SG, AnbuNeural)"}
           Voice::ta_SG_VenbaNeural => {"Microsoft Server Speech Text to Speech Voice (ta-SG, VenbaNeural)"}
           Voice::ta_LK_KumarNeural => {"Microsoft Server Speech Text to Speech Voice (ta-LK, KumarNeural)"}
           Voice::ta_LK_SaranyaNeural => {"Microsoft Server Speech Text to Speech Voice (ta-LK, SaranyaNeural)"}
           Voice::te_IN_MohanNeural => {"Microsoft Server Speech Text to Speech Voice (te-IN, MohanNeural)"}
           Voice::te_IN_ShrutiNeural => {"Microsoft Server Speech Text to Speech Voice (te-IN, ShrutiNeural)"}
           Voice::th_TH_NiwatNeural => {"Microsoft Server Speech Text to Speech Voice (th-TH, NiwatNeural)"}
           Voice::th_TH_PremwadeeNeural => {"Microsoft Server Speech Text to Speech Voice (th-TH, PremwadeeNeural)"}
           Voice::tr_TR_AhmetNeural => {"Microsoft Server Speech Text to Speech Voice (tr-TR, AhmetNeural)"}
           Voice::tr_TR_EmelNeural => {"Microsoft Server Speech Text to Speech Voice (tr-TR, EmelNeural)"}
           Voice::uk_UA_OstapNeural => {"Microsoft Server Speech Text to Speech Voice (uk-UA, OstapNeural)"}
           Voice::uk_UA_PolinaNeural => {"Microsoft Server Speech Text to Speech Voice (uk-UA, PolinaNeural)"}
           Voice::ur_IN_GulNeural => {"Microsoft Server Speech Text to Speech Voice (ur-IN, GulNeural)"}
           Voice::ur_IN_SalmanNeural => {"Microsoft Server Speech Text to Speech Voice (ur-IN, SalmanNeural)"}
           Voice::ur_PK_AsadNeural => {"Microsoft Server Speech Text to Speech Voice (ur-PK, AsadNeural)"}
           Voice::ur_PK_UzmaNeural => {"Microsoft Server Speech Text to Speech Voice (ur-PK, UzmaNeural)"}
           Voice::uz_UZ_MadinaNeural => {"Microsoft Server Speech Text to Speech Voice (uz-UZ, MadinaNeural)"}
           Voice::uz_UZ_SardorNeural => {"Microsoft Server Speech Text to Speech Voice (uz-UZ, SardorNeural)"}
           Voice::vi_VN_HoaiMyNeural => {"Microsoft Server Speech Text to Speech Voice (vi-VN, HoaiMyNeural)"}
           Voice::vi_VN_NamMinhNeural => {"Microsoft Server Speech Text to Speech Voice (vi-VN, NamMinhNeural)"}
           Voice::cy_GB_AledNeural => {"Microsoft Server Speech Text to Speech Voice (cy-GB, AledNeural)"}
           Voice::cy_GB_NiaNeural => {"Microsoft Server Speech Text to Speech Voice (cy-GB, NiaNeural)"}
           Voice::zu_ZA_ThandoNeural => {"Microsoft Server Speech Text to Speech Voice (zu-ZA, ThandoNeural)"}
           Voice::zu_ZA_ThembaNeural => {"Microsoft Server Speech Text to Speech Voice (zu-ZA, ThembaNeural)"}
        }
    }
}
